Export total_direct_reclaim metric to prometheus
prometheus/memcached_exporter pull request #227
Opened 2024-09-01 10:40 UTC by Vandit1604

fixes #136

2024-09-01 14:19 UTC, SuperQ requested changes

2024-09-01 14:19 UTC, SuperQ commented on pkg/exporter/exporter.go
> +			prometheus.BuildFQName(Namespace, "", "total_direct_reclaims"),
Must match Prometheus naming conventions.

```suggestion
			prometheus.BuildFQName(Namespace, "", "direct_reclaims_total"),
```

2024-09-01 15:12 UTC, Vandit1604 commented on pkg/exporter/exporter.go
> +			prometheus.BuildFQName(Namespace, "", "total_direct_reclaims"),
Done

2024-09-06 08:36 UTC, Vandit1604 commented
@SuperQ Is there anything else that needs to be done here to complete the PR?

2024-10-17 15:53 UTC, Sticksman approved these changes

2024-10-17 18:27 UTC, SuperQ commented on README.md
> +# TYPE memcached_total_direct_reclaims counter
This also needs to be updated.

2024-10-17 19:20 UTC, Vandit1604 commented on README.md
> +# TYPE memcached_total_direct_reclaims counter
Done.

2024-10-25 13:13 UTC, matthiasr approved these changes

2024-11-08 14:18 UTC, merged